### ISSUE TITLE
Data augmentation step before applying rotation

### ISSUE THREAD

**Issue by julian-carpenter** [Sara-Ahmed/SiT#9]
Hi Sara,

in your paper, you write: "We found that the network struggles to distinguish between the rotated image and the rotation of the flipped image as two different classes. **Instead, we included the horizontal flipping to the data augmentation step before applying rotation**, and hence, the network is trained to classify the image and the flipped image to the same class."

In:
https://github.com/Sara-Ahmed/SiT/blob/1767b9146f77883b101ac790ff24b1220ce8c2dd/datasets/datasets_utils.py#L31-L47

You do it the other way around, or am I mistaken? 
You first take the same batch, apply random rotation independently, and then apply the standard augmentation routine. So, in that case, the original image and the flipped one may have two different rotational classes, or not?

Thanks in advance for clarification,
Best,
Julian

**Comment by Sara-Ahmed** [comment]
In the text you referred to, it was mainly about "instead of having 8 classes for the rotation, we have only 4 classes and every image and its flipped version will belong to the same class.
But you are totally right, it is as mentioned in the paper, first horizontal flip and then rotation, these two lines should be before the rotation, 
     if transform is not None: 
         X1 = transform(X1) 
         X2 = transform(X2) 

I think that I interchanged them while cleaning the code. Thanks for pointing it out. I will fix it now.

**Comment by julian-carpenter** [comment]
Thanks for the clarification. I'll close the issue then.
